# Generated by Django 3.1.12 on 2025-11-10 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('organizacion', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('precio_boleta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.administradorevento')),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.AddField(
            model_name='boleta',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='core.evento'),
        ),
    ]
